version: '3'
services:
  db_dev:
    image: postgres:latest
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: task_manager_dev
    volumes:
      - ./pgdata/dev:/var/lib/postgresql/data

  db_test:
    image: postgres:latest
    ports:
      - '5433:5432'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: task_manager_test
    volumes:
      - ./pgdata/test:/var/lib/postgresql/data
