version: '3'
services:
  db_dev:
    image: postgres:latest
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: dev_user
      POSTGRES_PASSWORD: dev_password
      POSTGRES_DB: task_manager_dev
    volumes:
      - ./pgdata_dev:/var/lib/postgresql/data

  db_test:
    image: postgres:latest
    ports:
      - '5433:5432'
    environment:
      POSTGRES_USER: test_user
      POSTGRES_PASSWORD: test_password
      POSTGRES_DB: task_manager_test
    volumes:
      - ./pgdata_test:/var/lib/postgresql/data
